### ISSUE TITLE
ToastPlugin not loading properly

### ISSUE THREAD

**Issue by BerndNK** [grollmus/BuildNotifications#64]
It seems that loading the toast plugin indirectly through the dll, results in some errors. 
The mentioned assembly below is within the NuGet package "microsoft.windows.sdk.contracts"
Maybe it's a problem related to different versions of installed Windows SDK?

Warning: Warning 2019-09-29 12:35:16.3411 BuildNotifications.Core.Plugin.PluginLoader Exception while trying to load C:\Users\Bernd\source\repos\BuildNotifications\BuildNotifications\bin\Debug\netcoreapp3.0\win-x64\plugins\toast\ToastNotificationsPlugin.dllSystem.IO.FileLoadException: Could not load file or assembly 'Windows.Foundation.UniversalApiContract, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'. Operation is not supported. (0x80131515)
File name: 'Windows.Foundation.UniversalApiContract, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at BuildNotifications.Core.Plugin.PluginLoader.LoadPluginAssemblies(String folder)+MoveNext() in C:\Users\Bernd\source\repos\BuildNotifications\BuildNotifications.Core\Plugin\PluginLoader.cs:line 50

**Comment by TheSylence** [comment]
Okay I have no idea what the f its problem is...
